vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        poster_file:
            uri_prefix: /uploads/images/posters
            upload_destination: '%upload_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        actor_file:
            uri_prefix: /uploads/images/actors
            upload_destination: '%upload_directory_actor%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        director_file:
            uri_prefix: /uploads/images/directors
            upload_destination: '%upload_directory_director%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
      